[versions]
jade = "15.8.3+neoforge"
lombok = "8.7.1"

[libraries]
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
