name: Bug report
description: Report a bug where something is not working as expected.
title: "[:bug:Bug]: <title>"
labels: [ "bug" ]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Please make sure you have checked all these items before submitting your bug report.
      options:
        - label: "I have checked for existing issues, and have found none."
          required: true
        - label: "I have checked that this occurs on the latest version."
          required: true
  - type: textarea
    attributes:
      label: 🐛 Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ⚠️ Current behavior
      description: A clear and concise description of what happens. Attach screenshots here as necessary.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💣 Steps to reproduce
      description: How we can reproduce the behavior.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: ":information_source: Additional Information"
      description: Any additional information you wish to provide. Please add anything which did not fit into the other sections here.
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this bug report.
