name: Feature request
description: Suggest an idea for this project
title: "[✨Feature] "
labels: [ "feature" ]
body:
  - type: textarea
    attributes:
      label: ⚠️ Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💡 Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 🤚 Do you want to develop this feature yourself?
      options:
        - No
        - Yes
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this feature request.